const SongNames = [
"40",
"11 O'Clock Tick Tock",
"13 (There Is A Light)",
"4th Of July",
"A Celebration",
"A Day Without Me",
"A Different Kind Of Blue",
"A Man And A Woman",
"A Room At The Heartbreak Hotel",
"A Sort Of Homecoming",
"Acrobat",
"Ahimsa",
"Alex Descends Into Hell For A Bottle Of Milk",
"All Because Of You",
"All I Want Is You",
"Always",
"Always Forever Now",
"Amazing Grace",
"American Soul",
"An Cat Dubh",
"Angel Of Harlem",
"Angels Too Tied To The Ground",
"Another Day",
"Another Time Another Place",
"Babyface",
"Bad",
"Bang A Gong (Get It On)",
"Bass Trap",
"Beach Sequence",
"Beat On The Brat",
"Beautiful Day",
"Big Girls Are Best",
"Blow Your House Down",
"Book Of Your Heart",
"Boomerang",
"Boy/Girl",
"Breathe",
"Bullet The Blue Sky",
"California (There Is No End To Love)",
"Can't Help Falling In Love",
"Cedars Of Lebanon",
"Cedarwood Road",
"Christmas (Baby Please Come Home)",
"City Of Blinding Lights",
"Corpse (These Chains Are Way Too Lo",
"Crumbs From Your Table",
"Daddy's Gonna Pay For Your Crashed",
"Dancing Barefoot",
"Deep In The Heart",
"Desert Of Our Love",
"Desire",
"Dirty Day",
"Disappearing Act",
"Discotheque",
"Do You Feel Loved",
"Don't Take Your Guns To Town",
"Down All The Days",
"Drowning Man",
"Drunk Chicken",
"Electrical Storm",
"Elevation",
"Elvis Ate America",
"Elvis Presley & America",
"Endless Deep",
"Even Better Than The Real Thing",
"Everlasting Love",
"Every Breaking Wave",
"Everybody Loves A Winner",
"Exit",
"Fast Cars",
"Fez: Being Born",
"Fire",
"Flower Child",
"Fortunate Son",
"Get On Your Boots",
"Get Out Of Your Own Way",
"Gloria",
"God, Pt. II",
"Gone",
"Grace",
"Hallelujah Here She Comes",
"Happiness Is A Warm Gun",
"Hawkmoon 269",
"Heartland",
"Heaven And Hell",
"Hold Me, Thrill Me, Kiss Me, Kill M",
"Holy Joe",
"I Fall Down",
"I Still Haven't Found What I'm Look",
"I Threw A Brick Through A Window",
"I Will Follow",
"I'll Go Crazy If I Don't Go Crazy T",
"I'm Not Your Baby",
"If God Will Send His Angels",
"If You Wear That Velvet Dress",
"In A Little While",
"In God's Country",
"Indian Summer Sky",
"Invisible",
"Iris (Hold Me Close)",
"Is That All?",
"Ito Okashi",
"J.Swallow",
"Jesus Christ",
"Kite",
"Lady With The Spinning Head",
"Landlady",
"Last Night On Earth",
"Lemon",
"Levitate",
"Lights Of Home",
"Like A Song...",
"Love And Peace Or Else",
"Love Comes Tumbling",
"Love Is All We Have Left",
"Love Is Bigger Than Anything In Its",
"Love Is Blindness",
"Love Rescue Me",
"Love You Like Mad",
"Lucifer's Hands",
"Luminous Times",
"MLK",
"Magnificent",
"Miami",
"Miracle Drug",
"Miss Sarajevo",
"Mofo",
"Moment Of Surrender",
"Mothers Of The Disappeared",
"Mysterious Ways",
"Native Son",
"Near The Island",
"Neon Lights",
"New Year's Day",
"New York",
"Night And Day",
"No Line On The Horizon",
"North And South Of The River",
"Numb",
"October",
"Oh Berlin",
"One",
"One Minute Warning",
"One Step Closer",
"One Tree Hill",
"Ordinary Love",
"Original Of The Species",
"Out Of Control",
"Paint It Black",
"Party Girl",
"Peace On Earth",
"Please",
"Plot 180",
"Pride (In The Nname Of Love)",
"Promenade",
"Race Against Time",
"Raised By Wolves",
"Red Flag Day",
"Red Hill Mining Town",
"Red Light",
"Rejoice",
"Rise Up",
"Running To Stand Still",
"Salome",
"Satellite Of Love",
"Saturday Night",
"Scarlet",
"Seconds",
"Shadows And Tall Trees",
"Silver & Gold",
"Sixty Seconds In Kingdom Come",
"Sleep Like A Baby Tonight",
"Slow Dancing",
"Slug",
"Smile",
"So Cruel",
"Some Days Are Better Than Others",
"Sometimes You Can't Make It On Your",
"Song For Someone",
"Spanish Eyes",
"Speed Of Life",
"Stand Up Comedy",
"Staring At The Sun",
"Stateless",
"Stay (Faraway, So Close!)",
"Stories For Boys",
"Stranger In A Strange Land",
"Street Mission",
"Stuck In A Moment You Can't Get Out",
"Summer Of Loves",
"Summer Rain",
"Sunday Bloody Sunday",
"Surrender",
"Sweetest Thing",
"Take Me To The Clouds Above",
"The Ballad Of Ronnie Drew",
"The Blackout",
"The Crystal Ballroom",
"The Electric Co.",
"The First Time",
"The Fly",
"The Fool",
"The Ground Beneath Her Feet",
"The Hands That Built America",
"The Little Things That Give You Awa",
"The Miracle (Of Joey Ramone)",
"The Ocean",
"The Playboy Mansion",
"The Refugee",
"The Saints Are Coming",
"The Showman",
"The Troubles",
"The Unforgettable Fire",
"The Wanderer",
"Theme From Let's Go Native",
"Theme From The Swan",
"Things To Make And Do",
"This Is Where You Can Reach Me Now",
"Three Sunrises",
"Tomorrow",
"Touch",
"Treasure (Whatever Happened To Pete",
"Trip Through Your Wires",
"Tryin' To Throw Your Arms Around Th",
"Twilight",
"Two Hearts Beat As One",
"Ultraviolet (Light My Way)",
"Unchained Melody",
"United Colours",
"Unknown Caller",
"Until The End Of The World",
"Van Diemen's Land",
"Vertigo",
"Volcano",
"Wake Up Dead Man",
"Walk On",
"Walk To The Water",
"Wave Of Sorrow (Birdland)",
"When I Look At The World",
"When Love Comes To Town",
"Where Did It All Go Wrong?",
"Where The Streets Have No Name",
"White As Snow",
"Who's Gonna Ride Your Wild Horses",
"Wild Honey",
"Window In The Skies",
"Wire",
"With A Shout (Jerusalem)",
"With Or Without You",
"Xanax and Wine",
"Yahweh",
"Yoshino Blossom",
"You're The Best Thing About Me",
"Your Blue Room",
"Zoo Station",
"Zooropa"
];

export function getMatchingSongs(song) {
  switch(song) {
    case "Alex Descends Into Hell For A Bottle Of Milk": return ["Alex Descends Into Hell For A Bottl"]; break;
    case "Discotheque": return ["Discotheque", "Discothèque"]; break;
    case "Fire": case "Saturday Night": return ["Fire", "Saturday Night"]; break;
    case "New Year's Day": return ["New Year's D"]; break;
    case "Numb": case "Down All The Days": return ["Numb", "Down All The Days"]; break;
    case "One": return ["One", "One ("]; break;
    case "Party Girl": return ["Party Gir"]; break;
    default: return [song]
  }
};

export function getNonMatchingSongs(song) {
  switch(song) {
    case "40": return ["440"]; break;
    case "Always": return ["Always F"]; break;
    case "California (There Is No End To Love)": return ["California (There Is No End To Love"]; break;
    case "Even Better Than The Real Thing": return ["Even Better"]; break;
    case "Everybody Loves A Winner": return ["Everybody Loves A Win"]; break;
    case "Fire": case "Saturday Night": return ["The Unfogettable Fire"]; break;
    case "New York": return ["New York 7"]; break;
    case "One": return ["As One", "Gone", "Honey", "Ramone", "Someone", "One M", "One S", "One T"]; break;
    case "Wire": return ["Wires"]; break;
    default: return ["2222"]
  }
};


export default SongNames;
